apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: udagram-reverseproxy
  namespace: default
spec:
  ports:
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: "80"
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    service: reverseproxy
  type: LoadBalancer