language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# build feed API container
  - cd $TRAVIS_BUILD_DIR/udagram-api/feed && npm install && npm run build
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed bw120/udagram-api-feed:latest

# build users API container
  - cd $TRAVIS_BUILD_DIR/udagram-api/users && npm install && npm run build
  - docker build -t udagram-api-users .
  - docker tag udagram-api-users bw120/udagram-api-users:latest

# build frontend container
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend bw120/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bw120/udagram-api-feed
  - docker push bw120/udagram-api-users
  - docker push bw120/udagram-frontend